### ISSUE TITLE
No Font With Wine

### ISSUE THREAD

**Issue by Annwan** [CPULL/Retro-Game-Engine#1]
Runs well with Wine on Linux at the exception that the main menu and the dev tools does not have any text

Still pong is great fun (but you cant win)

All my encouragements for this nice project

**Comment by CPULL** [comment]
I will do a Linux build. 
The main menu is done directly in Unity, and has some problems because it is done using Text class and not TextMeshPro.

**Comment by CPULL** [comment]
Fixed here: https://github.com/CPULL/Retro-Game-Engine/releases/tag/0.1a.Linux
